Repository nneaning/meaning_Server, pull requests merged in 2021-01, with the labels that each got.

#5 [feat]: eslint, prettier 설정 추가
  .eslintrc.json
  .prettierrc.json
  models/bookComment.js
  models/diary.js
  models/group.js
  models/timeStamp.js
  models/todaysPromise.js
  models/user.js
  package.json
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 😎 enhancement, 🧑🏻‍💻 상수

#7 [fix]: DB 컬럼 변경 및 미들웨어를 활용한 토큰 활용 리팩토링
  .gitignore
  app.js
  controller/authController.js
  controller/userController.js
  middlewares/authUtil.js
  models/member.js
  models/post.js
  models/user.js
  modules/jwt.js
  package.json
  public/stylesheets/style.css
  routes/auth/index.js
  routes/index.js
  routes/users/index.js
  routes/util/isLoggedIn.js
  service/userService.js
  views/error.jade
  views/index.jade
  views/layout.jade
Labels: ☝🏻 P0, 🐜 Server, 🚀 Issue, 🛠 Fix, 🧑🏻‍💻 상수

#16 [feat]: multer 사전 설정
  modules/multer.js
  package.json
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 💁🏻 기문, 😎 enhancement

#17 [fix]: 잘못된 s3의 버켓 위치를 수정
  modules/multer.js
Labels: 🐜 Server, 🐞 Bug, 💁🏻 기문, 🛠 Fix

#22 [feat]: 마이페이지 API 개발 페이징 구현
  controller/userController.js
  modules/responseMessage.js
  routes/users/index.js
  service/userService.js
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 🧑🏻‍💻 상수

#29 [docs]: README 수정
  README.md
Labels: ☝🏻 P0, 🐜 Server, 📕 documentation, 🧑🏻‍💻 상수

#26 [feat]: 타임스탬프 작성 API
  controller/timeStampController.js
  models/timeStamp.js
  models/user.js
  modules/dateTimeModule.js
  modules/missionStatus.js
  modules/responseMessage.js
  package.json
  routes/index.js
  routes/timeStamp/index.js
  service/timeStampService.js
  service/userService.js
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 💁🏻 기문, 😎 enhancement

#32 [fix]: 타임스탬프 작성 요청시, 파라미터 누락 검증 로직 추가
  controller/timeStampController.js
Labels: ☝🏻 P0, 🐜 Server, 💁🏻 기문, 🛠 Fix

#33 [feat] 온보드 정보 등록 요청 API
  controller/userController.js
  modules/responseMessage.js
  routes/users/index.js
  service/userService.js
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 💁🏻 기문, 😎 enhancement

#36 [feat]: groupImage, groupProfile 테이블 추가
  controller/userController.js
  models/groupImage.js
  models/groupProfile.js
  models/index.js
  modules/dateTimeModule.js
  modules/responseMessage.js
  routes/index.js
  routes/timeStamp.js
  routes/timeStamp/index.js
  routes/user.js
  service/userService.js
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 🧑🏻‍💻 상수

#38 [feat] 그룹 참가 API
  controller/groupController.js
  modules/responseMessage.js
  routes/group.js
  service/groupService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 💁🏻 기문, 😎 enhancement

#39 [feat] 그룹 이미지 등록 API
  controller/groupController.js
  modules/multer.js
  modules/responseMessage.js
  routes/group.js
  routes/users.js
  service/groupService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 😎 enhancement, 🧑🏻‍💻 상수

#40 [fix]: 그룹생성시 그룹프로필 테이블에 데이터가 생성되는 로직 추가
  controller/groupController.js
  modules/responseMessage.js
  service/groupService.js
Labels: ☝🏻 P0, 🐜 Server, 😎 enhancement, 🛠 Fix, 🧑🏻‍💻 상수

#42 [feat]: 타임스탬프 작성 API, 그룹 이용자용
  controller/timeStampController.js
  modules/responseMessage.js
  service/postService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 😎 enhancement

#44 [GET] 그룹 내 피드(포스트) 요청 API
  controller/groupController.js
  modules/responseMessage.js
  routes/group.js
  service/groupService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 💁🏻 기문, 😎 enhancement

#48 [feat]: 오늘 하루 다짐 작성 및 제공 API
  controller/userController.js
  models/todaysPromise.js
  modules/dateTimeModule.js
  modules/responseMessage.js
  routes/user.js
  service/postService.js
  service/userService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 💁🏻 기문, 🧑🏻‍💻 상수

#54 [feat]: 독후감 API 개발 추가
  controller/userController.js
  models/bookComment.js
  modules/responseMessage.js
  routes/user.js
  service/userService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 🧑🏻‍💻 상수

#53 [feat]: 자기회고 및 일기 작성 API 추가
  controller/userController.js
  modules/responseMessage.js
  routes/user.js
  service/userService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 🧑🏻‍💻 상수

#52 [feet] 그룹 설정 정보 제공 API
  controller/groupController.js
  controller/timeStampController.js
  modules/dateTimeModule.js
  modules/responseMessage.js
  routes/group.js
  service/groupService.js
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 💁🏻 기문, 😎 enhancement

#55 [feat]: 그룹리스트 상세보기 API
  controller/groupController.js
  controller/userController.js
  modules/responseMessage.js
  routes/group.js
  routes/user.js
  service/groupService.js
  service/userService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 🧑🏻‍💻 상수

#59 [fix]: 로그인 API 닉네임과 기상시간 제공하는 로직 추가
  controller/userController.js
Labels: 🐜 Server, 🛠 Fix, 🧑🏻‍💻 상수

#58 [fix] 그룹리스트 API SQL 작성
  controller/groupController.js
  controller/timeStampController.js
  controller/userController.js
  modules/responseMessage.js
  package.json
  routes/group.js
  service/groupService.js
Labels: ☝🏻 P0, 🐜 Server, 🛠 Fix, 🧑🏻‍💻 상수

#60 [fix]: 그룹리스트 API 개인사용자 정보 누락 문제 해결
  controller/groupController.js
  service/groupService.js
Labels: 🐜 Server, 🛠 Fix, 🧑🏻‍💻 상수

#61 [feat]: 그룹 생성시 생성된 그룹의 id 응답
  controller/groupController.js
Labels: ☝🏻 P0, 🎙 Feat, 💁🏻 기문, 😎 enhancement

#62 [fix]: 일기 작성 API 응답 문구 변경 및 내용 검증 로직 삭제
  controller/userController.js
  modules/responseMessage.js
Labels: ✌🏻 P1, 🐜 Server, 💁🏻 기문, 🛠 Fix

#67 [fix]: 마이페이지 API Service 수정
  service/userService.js
Labels: 🐜 Server, 🛠 Fix, 🧑🏻‍💻 상수

#70 [refactor]: 그룹 내부 피드 API 요청 URL 변경
  routes/group.js
Labels: ☝🏻 P0, 🐜 Server, 💁🏻 기문, 🛠 Fix

#66 [feat] 타임스탬프 상세보기
  controller/timeStampController.js
  modules/responseMessage.js
  routes/timeStamp.js
  service/timeStampService.js
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 💁🏻 기문, 😎 enhancement

#72 [feat]: 캘린더 API 구현
  controller/timeStampController.js
  controller/userController.js
  modules/responseMessage.js
  routes/timeStamp.js
  service/timeStampService.js
Labels: ✌🏻 P1, 🎙 Feat, 🐜 Server, 🧑🏻‍💻 상수

#77 [fix]: 타임스탬프 작성 API 응답 오타 수정
  controller/timeStampController.js
Labels: 🐜 Server, 💁🏻 기문, 🛠 Fix

#78 [fix]: 짧은 독서 작성 중복 처리 로직 제거
  controller/userController.js
  service/userService.js
Labels: ✌🏻 P1, 🐜 Server, 🛠 Fix, 🧑🏻‍💻 상수

#80 [feat]: 사용자가 가입된 그룹 정보 요청
  controller/groupController.js
  modules/responseMessage.js
  routes/group.js
Labels: ☝🏻 P0, 🎙 Feat, 🐜 Server, 💁🏻 기문, 😎 enhancement

#81 [refactor]: 그룹리스트 조회 API가 더 이상 myGroup을 포함하지 않음
  controller/groupController.js
  modules/responseMessage.js
Labels: ☝🏻 P0, 🐜 Server, 💁🏻 기문

#82 [fix]: 그룹 설정 정보 응답에 그룹 생성일 포함하여 응답
  controller/groupController.js
Labels: ☝🏻 P0, 🐜 Server, 💁🏻 기문, 🛠 Fix

#83 [fix]: 잘못된 비밀번호로 로그인을 시도했을 때 응답 메세지가 제대로 송신되지 않는 문제 해결
  controller/userController.js
  modules/encryptModule.js
  service/userService.js
Labels: 🐜 Server, 💁🏻 기문, 🛠 Fix

#84 [fix]: 그룹 생성 시 그룹명 중복 검사 및 응답 코드 구분화
  controller/groupController.js
  modules/responseMessage.js
  service/groupService.js
Labels: ☝🏻 P0, 🐜 Server, 💁🏻 기문, 🛠 Fix

#85 [fix]: 그룹생성 API에서 groupImage를 제공받지 못한 에러 해결
  controller/groupController.js
Labels: ☝🏻 P0, 🐜 Server, 🛠 Fix, 🧑🏻‍💻 상수

#88 [fix]: 그룹생성 API에서 그룹 생성 시, 그룹 이미지가 생성되지 않은 에러 해결
  controller/groupController.js
  service/groupService.js
Labels: ☝🏻 P0, 🐜 Server, 🛠 Fix, 🧑🏻‍💻 상수

#75 [fix]: README 수정
  README.md
  controller/groupController.js
  controller/userController.js
  package.json
Labels: 🐜 Server, 📕 documentation, 🧑🏻‍💻 상수
